#CREATE DATABASE IF NOT EXISTS djava_db;#
#USE djava_db;#

DROP TABLE IF EXISTS menu;

CREATE TABLE menu (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  price INT,
  image VARCHAR(255)
);

INSERT INTO menu (name, price, image) VALUES
('Original Tea', 3000, 'ori-tea.jpeg'),
('Anggur Tea', 5000, 'anggur-tea.jpeg'),
('Lemon Tea', 5000, 'lemon-tea.jpeg'),
('Markisa Tea', 5000, 'markisa-tea.jpeg'),
('Strowberry Tea', 5000, 'strowbery-tea.jpeg'),
('Melon Tea', 5000, 'melon-tea.jpeg'),
('Mangga Tea', 5000, 'mangga-tea.jpeg'),
('Lecy Tea', 5000, 'leci-tea.jpeg'),
('Jeruk Tea', 5000, 'jeruk-tea.jpeg'),
('Apple Tea', 5000, 'apel-tea.jpeg'),
('Blackcurrent Tea', 5000, 'blackbery-tea.jpeg'),
('Milk Tea', 7000, 'milk-tea.jpeg'),
('Milky Peach', 8000, 'milky-peach.jpeg'),
('Coklat Tea', 8000, 'coklat-tea.jpeg'),
('Matcha Tea', 8000, 'macha-tea.jpeg'),
('Taro Tea', 8000, 'taro-tea.jpeg'),
('Milo Tea', 8000, 'milo-tea.jpeg'),
('Oreo Tea', 8000, 'oreo-tea.jpeg'),
('Classic Tiramisu', 8000, 'tiramisu.jpeg'),
('Royal Choco', 10000, 'royal-choco.jpeg'),
('Cookies and Cream', 10000, 'cokis.jpeg'),
('Silverqueen', 10000, 'silverquen.jpeg'),
('Choco Taro', 10000, 'choco-taro.jpeg'),
('Choco Matcha', 10000, 'choco-macha.jpeg'),
('Caramel Latte', 8000, 'caramel-coffe.jpeg'),
('Milky Latte', 8000, 'milky-latte.jpeg'),
('Cappucino', 8000, 'capucino.jpeg'),
('Brown Sugar', 8000, 'brown-sugar.jpeg'),
('Taro Coffee', 10000, 'taro-coffee.jpeg'),
('Matcha Coffee', 10000, 'macha-coffe.jpeg'),
('Milo Coffee', 10000, 'milo-coffe.jpeg'),
('Coklat Coffee', 10000, 'coklat-coffe.jpeg'),
('Tiramisu Coffee', 10000, 'tiramisu.jpeg'),
('Milky Coffee', 7000, 'milky-coffee.jpeg'),
('Choco Coffee', 7000, 'choco-coffe.jpeg'),
('Brown Sugar Coffee', 7000, 'brown-sugar.jpeg'),
('Americano', 7000, 'coffee-boom.jpeg'),
('Coffee Boom', 7000, 'coffee-boom.jpeg'),
('Caramel Coffee', 7000, 'caramel-coffe.jpeg'),
('Es Susu', 6000, 'es-susu.jpeg'),
('Pink Lava', 7000, 'pink-lava.jpeg'),
('Josh Susu', 7000, 'josh-susu.jpeg'),
('Coklat Oreo', 7000, 'coklat-oreo.jpeg'),
('Bublegum', 7000, 'bublegum.jpeg'),
('Mojito Ori', 8000, 'mojito.jpeg'),
('Mojito Jeruk', 10000, 'mojito-jeruk.jpeg'),
('Mojito Melon', 10000, 'mojito-melon.jpeg'),
('Mojito Strowberry', 10000, 'mojito-strowbery.jpeg'),
('Mojito Leci', 10000, 'mojito.jpeg'),
('Mojito Markisa', 10000, 'mojito-markisa.jpeg'),
('Mojito Anggur', 10000, 'mojito-anggur.jpeg'),
('Mojito Nanas', 10000, 'mojito-jeruk.jpeg'),
('Request Bento Cake', 25000, 'bento-cake.jpeg'),
('Mini Cake', 5000, 'mini-cake.jpeg');
